#ifndef INCLUDE_BASE_CONF_H
#define INCLUDE_BASE_CONF_H

/**
 * Contiene le costanti di configurazione
 */

const PROGMEM char *   CONF_ADMIN_PASSWORD              = "admin";
const PROGMEM char *   CONF_ADMIN_USERNAME              = "admin";

#define CONF_ARDUINO_OTA

#define CONF_BMP280
#ifdef CONF_BMP280
#endif

#define CONF_DHT
#ifdef CONF_DHT
const PROGMEM uint32_t CONF_DHT_READ_INTERVAL_MIN       = 5000;
#endif

const PROGMEM char *   CONF_LOG_LEVEL                   = "i";

const PROGMEM uint32_t CONF_MONITOR_BAUD_RATE           = 115200;

// Valore per Europe/Rome in https://github.com/nayarsystems/posix_tz_db/blob/master/zones.csv
const PROGMEM char *   CONF_TIME_ZONE                   = "CET-1CEST,M3.5.0,M10.5.0/3";

#define CONF_WIFI
#ifdef CONF_WIFI

#define CONF_WEB
#ifdef CONF_WEB
const PROGMEM char *   CONF_WEB_HTML_TITLE              = "ESP8266";
const PROGMEM uint16_t CONF_WEB_HTTP_PORT               = 80;

#define CONF_WEB_HTTPS
#ifdef CONF_WEB_HTTPS
/*
const PROGMEM char *   CONF_WEB_HTTPS_CERT              = R"EOF(
-----BEGIN CERTIFICATE-----
MIICGDCCAYECAQIwDQYJKoZIhvcNAQELBQAwVDELMAkGA1UEBhMCREUxCzAJBgNV
BAgMAkJFMQ8wDQYDVQQHDAZCZXJsaW4xEjAQBgNVBAoMCU15Q29tcGFueTETMBEG
A1UEAwwKbXljYS5sb2NhbDAeFw0yNDAyMTIxMjAwNTlaFw0zNDAyMDkxMjAwNTla
MFUxCzAJBgNVBAYTAkRFMQswCQYDVQQIDAJCRTEPMA0GA1UEBwwGQmVybGluMRIw
EAYDVQQKDAlNeUNvbXBhbnkxFDASBgNVBAMMC2VzcDMyLmxvY2FsMIGfMA0GCSqG
SIb3DQEBAQUAA4GNADCBiQKBgQDND5F9H6zW+hIBsy3sV7/eE26Cp6pXBA37M8GG
eFXYoeLHzNffdXYdXFQONIjSOxn5X3gTBY2YppBvgzH9TCiN8Y2tXH2r6QpBnZrf
xJBQAP1RmNReE6RTJ+l/4tJ8LLBe7Hs+jyCq9sFwF8b09thrUb2q1IwrlK+tOa8s
W77HXwIDAQABMA0GCSqGSIb3DQEBCwUAA4GBAGh9FURupOK9PrQvLvH68/3MA3ZG
kuO7V+xHY9G5lEMrg5fFY3zKJt31gYL9PXyEcpQwJd9+NXDneBrKWXs5Bxoy/sEI
KT8BDPqHc0SRoAFnznvfh9c218YfaqcypeVtv37v35V6tQeOwCsr54HTBjZlFCPT
4IxEwP0+Ya5bpHwB
-----END CERTIFICATE-----
)EOF";
const PROGMEM char *   CONF_WEB_HTTPS_CERT_KEY          = R"EOF(
-----BEGIN PRIVATE KEY-----
MIICXgIBAAKBgQDND5F9H6zW+hIBsy3sV7/eE26Cp6pXBA37M8GGeFXYoeLHzNff
dXYdXFQONIjSOxn5X3gTBY2YppBvgzH9TCiN8Y2tXH2r6QpBnZrfxJBQAP1RmNRe
E6RTJ+l/4tJ8LLBe7Hs+jyCq9sFwF8b09thrUb2q1IwrlK+tOa8sW77HXwIDAQAB
AoGBAK2MoYuORU/kcVzy8sj2MzKWq470rBvdGKAj24QdUDp6OF71JTbASOjsfU9Q
cwPKdV8yx4MBzicFwXQ/Sw2faSnEQtnJIanYhXsV8PZh62h5mfbnQPEHTzoY/LN/
JXxn5e4hMNm6ruUBr0OdcOvxvAvRiBEC4m6xzBYlc2KRKW4xAkEA9H9envByR8Jp
UqNWwv9ah1Ou2rKkJGzdTYivfEIzEUs20dplO7pmWgq5mq9wmFzYWr+xtvSjHtFM
sDulwrTsTQJBANa1PRTzwdloUildxmDPuiAQ0PAI22UtSAxlib0sJE5sAX7MHB0E
ej2r3E3msESi4/VgkM1gzhs6H4HryRzt6FsCQQClY3NyOFxVxmDQkcUi6vEmEal6
LtVx/mJFDG0ItQ8uZ56RnhZUrOaHijG7PWoA5u1DleB1Tk75jcM+g1rBtvkRAkEA
h4571xujGwE7RnS3R+4+w/n6AGKHKhTxtSnyUaZp8b1NIGH7qfJmv0MfX2uzhFIX
fJeQNKrW1efXdq6IFiS6mwJAX+w1DIXu44zFSgeiexFJQ7yNInI6vOLGUHb1i1v+
/m5Xscy7TASIMLACJFculTRvvmlbQot0kSpb+RGs03OMfw==
-----END PRIVATE KEY-----
)EOF";
*/
static const char CONF_WEB_HTTPS_CERT[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIIC6jCCAlOgAwIBAgIUZIw0cBcWDPJZe8ZIDu6bDqdwwvwwDQYJKoZIhvcNAQEL
BQAwejELMAkGA1UEBhMCUk8xCjAIBgNVBAgMAUIxEjAQBgNVBAcMCUJ1Y2hhcmVz
dDEbMBkGA1UECgwST25lVHJhbnNpc3RvciBbUk9dMRYwFAYDVQQLDA1PbmVUcmFu
c2lzdG9yMRYwFAYDVQQDDA1lc3A4MjY2LmxvY2FsMB4XDTE5MDQxMzE1NTMzOFoX
DTIwMDQxMjE1NTMzOFowejELMAkGA1UEBhMCUk8xCjAIBgNVBAgMAUIxEjAQBgNV
BAcMCUJ1Y2hhcmVzdDEbMBkGA1UECgwST25lVHJhbnNpc3RvciBbUk9dMRYwFAYD
VQQLDA1PbmVUcmFuc2lzdG9yMRYwFAYDVQQDDA1lc3A4MjY2LmxvY2FsMIGfMA0G
CSqGSIb3DQEBAQUAA4GNADCBiQKBgQCiZmrefwe6AwQc5BO+T/18IVyJJ007EASn
HocT7ODkL2HNgIKuQCnPimiysLh29tL1rRoE4v7qtpV4069BrMo2XqFvZkfbZo/c
qMcLJi43jSvWVUaWvk8ELlXNR/PX4627MilhC4bLD57VB7Q2AF4jrAVhBLzClqg0
RyCS1yab+wIDAQABo20wazAdBgNVHQ4EFgQUYvIljCgcnOfeRn1CILrj38c7Ke4w
HwYDVR0jBBgwFoAUYvIljCgcnOfeRn1CILrj38c7Ke4wDwYDVR0TAQH/BAUwAwEB
/zAYBgNVHREEETAPgg1lc3A4MjY2LmxvY2FsMA0GCSqGSIb3DQEBCwUAA4GBAI+L
mejdOgSCmsmhT0SQv5bt4Cw3PFdBj3EMFltoDsMkrJ/ot0PumdPj8Mukf0ShuBlL
alf/hel7pkwMbXJrQyt3+EN/u4SjjZZJT21Zbxbmo1BB/vy1fkugfY4F3JavVAQ/
F49UaclGs77AVkDYwKlRh5VWhmnfuXPN6NXkfV+z
-----END CERTIFICATE-----
)EOF";
static const char CONF_WEB_HTTPS_CERT_KEY[] PROGMEM =  R"EOF(
-----BEGIN PRIVATE KEY-----
MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAKJmat5/B7oDBBzk
E75P/XwhXIknTTsQBKcehxPs4OQvYc2Agq5AKc+KaLKwuHb20vWtGgTi/uq2lXjT
r0GsyjZeoW9mR9tmj9yoxwsmLjeNK9ZVRpa+TwQuVc1H89fjrbsyKWELhssPntUH
tDYAXiOsBWEEvMKWqDRHIJLXJpv7AgMBAAECgYA5Syqu3mAKdt/vlWOFw9CpB1gP
JydvC+KoVvPOysY4mqLFjm4MLaTSjIENcZ1SkxewBubkDHVktw+atgvhfqVD4xnC
ewMpuN6Rku5A6EELhUoDrgMEt6M9D/0/iPaMm3VDtLXJq5SuKTpnM+vyE4/uM2Gu
4COfL4GQ0A5KWTzGcQJBANfpU/kwdZf8/oaOvpNZPGRsryjIXXuWMzKKM+M1RqSA
UQV596MGXjo8k8YG/A99rTmVhbeTMC2/7gIyGTePe/kCQQDAjZg2Ujz7wY3gf1Fi
ZETL7DHsss74sZyWZI490yIX0TQqKpXqEIKlkV+UZTOoSZiAaUyPjokblPmTkKfu
uMyTAkBIBjfS+o1fxC+L53Y/ZRc2UOMlcaFtpq8xftTMSGtmWL+uWf93zJoGR0rs
VkwjRsNQYEaY9Gqv+ESHSvsKg7zRAkEAoOLuhpzqVZThHe5jqumKzjS5dkPlScjl
xIeaji/msa3cf0r73goTj5HLIev5YKi1or3Y+a4oA4LTkifxGTcRvwJBAJB+qUE6
y8y+4yxStsWu362tn2o4EjyPL2UGc40wtlQng2GzPZ20+xVYcLxsJXE5/Jqg8IeI
elVVC46RfjDK9G0=
-----END PRIVATE KEY-----
)EOF";
const PROGMEM uint16_t CONF_WEB_HTTPS_PORT              = 443;
const PROGMEM char *   CONF_WEB_HTTPS_NAME              = "esp8266";
#endif

const PROGMEM uint16_t CONF_WEB_REDIRECT_REFRESH_MIN    = 5000;
const PROGMEM uint16_t CONF_WEB_UPLOAD_LIMIT            = 10240;
const PROGMEM char *   CONF_WEB_URI_CONFIG              = "/config";
const PROGMEM char *   CONF_WEB_URI_CONFIG_RESET        = "/config/reset";
const PROGMEM char *   CONF_WEB_URI_CONFIG_UPLOAD       = "/config/upload";
const PROGMEM char *   CONF_WEB_URI_FIRMWARE_UPDATE     = "/firmware/update";
const PROGMEM char *   CONF_WEB_URI_RESET               = "/reset";
#endif

const PROGMEM char *   CONF_WIFI_AP_IP                  = "192.168.12.1";
const PROGMEM char *   CONF_WIFI_AP_PSWD                = "esp8266";
const PROGMEM char *   CONF_WIFI_AP_SSID                = "esp8266";
const PROGMEM uint32_t CONF_WIFI_CHECK_INTERVAL_MIN     = 60000;
const PROGMEM uint32_t CONF_WIFI_CHECK_THRESHOLD        = 300000;
const PROGMEM uint32_t CONF_WIFI_CONN_TIMEOUT_MS        = 10000;
const PROGMEM uint8_t  CONF_WIFI_COUNT                  = 3;
const PROGMEM uint8_t  CONF_WIFI_MODE                   = 1;
const PROGMEM uint32_t CONF_WIFI_MODE_LIMIT             = 180000;
const PROGMEM char *   CONF_WIFI_NAME                   = "esp8266";
const PROGMEM char *   CONF_WIFI_NTP_SERVER             = "pool.ntp.org";
const PROGMEM uint32_t CONF_WIFI_NTP_INTERVAL           = 300000;
const PROGMEM uint32_t CONF_WIFI_NTP_INTERVAL_MIN       = 60000;

#endif

#endif
