name: 'ESP32 Project'
env:
  version: ${{ github.ref_name }}-v1.0
on:
  workflow_dispatch:
  push:
    branches:
      - 'flex'
permissions:
  contents: write
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  compile:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Arduino Compile
        run: tools/arduino-cli.exe compile -e -m esp32 --build-property build.defines='-DCOMPILE_VERSION="${{ env.version }}"'
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.version }}.${{ github.run_number }}
          name: Release ${{ env.version }}.${{ github.run_number }}
          body: |
            Changes in this Release
            ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
          files: |
            build/esp32.esp32.esp32/esp321go.ino.bin
            build/esp32.esp32.esp32/esp321go.ino.elf
            build/esp32.esp32.esp32/esp321go.ino.partitions.bin
