name: 'Arduino Release'
on:
  workflow_dispatch:
  push:
permissions:
  contents: write
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  compile:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Arduino Compile
        run: tools/arduino-cli.exe compile -e -m esp32
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}-v1.0.${{ github.run_number }}
          name: Release ${{ github.ref_name }}-v1.0.${{ github.run_number }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
          files: |
            build/esp32.esp32.esp32/esp321go.ino.bin
            build/esp32.esp32.esp32/esp321go.ino.elf
            build/esp32.esp32.esp32/esp321go.ino.partitions.bin
