name: 'Arduino Compile'
on:
  workflow_dispatch:
  push:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  compile:
    run-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Arduino Compile
        run: tools/arduino.exe
